### ISSUE TITLE
Necesito que actives la wiki para poder empezar a realizar el manual de usuario de tu programa

### ISSUE THREAD

**Issue by Zenonperez** [AlbertValado/DI04_Usability#1]
Puedes activar la wiki en "settings" y en "features" marcar la casilla de "wikis" asegurate tambien de marcar la casilla de solo colaboradores.

![image](https://github.com/AlbertValado/DI04_Usability/assets/148801600/c2c30bc1-213b-44bf-8706-e76d85505db1)

**Comment by AlbertValado** [comment]
Hecho!
